### ISSUE TITLE
Checklist: Use cases

### ISSUE THREAD

**Issue by edward62740** [edward62740/SC2006-Project#10]
The following use cases are **complete** (with required follow-up).

- [x] 1-1: Decoupled from 4-1
- [x] 1-2: Update SD
- [x] 1-3: Update SD
- [x] 1-4: Update SD
- [x] 1-5:
- [x] 1-6:
- [x] 1-7: Partial
- [x] 1-8:
- [x] 1-9:
- [x] 2-1:
- [x] 2-2:
- [x] 2-3:
- [x] 3-1:
- [x] 3-2:
- [x] 3-3:
- [x] 4-1: Require acceptance from those doing Vendor, Admin
- [x] 4-2: Require acceptance from those doing Vendor, Admin
- [x] 4-3:

The non-functional requirements:
- [x] Responsive UI: Subject to change
- [x] Screen size adaptation/no clipping:
- [x] Fast start-up (5s):
- [x] 90% DB retrieval in 1s: True where database size <1.3MB

Some architectural design choices..
- [x] MVC (or at least, an approximation)
- [x] Generic object (cloud) DB w/ CRUD ops
- [x] OneMap (implemented as iframe for ease of use)
- [x] Factory pattern for parameterized generic classes
- [x] Service locator pattern for lifecycle management of DB
- [x] Adapter pattern for viewholders, recyclerview etc
- [x] Strategy pattern for services
- [x] Singleton pattern for controllers
- [x] ISP, OCP, LSP etc.
